### ISSUE TITLE
NoClassDefFoundError exception of [Ljava/beans/PropertyDescriptor]

### ISSUE THREAD

**Issue by FernandoCCNunes** [ceridwen-com/ceridwen-standard-interchange-protocol-library#7]
Hi there, I'm am trying to implement your library to use with KOHA but I keep getting this exception 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.guia.app, PID: 985
    java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/beans/PropertyDescriptor;
        at org.apache.commons.beanutils.DefaultIntrospectionContext.<clinit>(DefaultIntrospectionContext.java:40)
        at org.apache.commons.beanutils.PropertyUtilsBean.fetchIntrospectionData(PropertyUtilsBean.java:2241)
        at org.apache.commons.beanutils.PropertyUtilsBean.getIntrospectionData(PropertyUtilsBean.java:2226)
        at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:954)
        at org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptor(PropertyUtils.java:498)
        at com.ceridwen.circulation.SIP.messages.Message.encode(Message.java:307)
        at com.ceridwen.circulation.SIP.messages.Message.encode(Message.java:285)
        at com.ceridwen.circulation.SIP.transport.Connection.send(Connection.java:215)
        at com.guia.app.activities.TestActivity$performCheckOut$1$1.invokeSuspend(TestActivity.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.PropertyDescriptor" on path: DexPathList[[zip file "/data/app/com.guia.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.guia.app-1/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.apache.commons.beanutils.DefaultIntrospectionContext.<clinit>(DefaultIntrospectionContext.java:40) 
        at org.apache.commons.beanutils.PropertyUtilsBean.fetchIntrospectionData(PropertyUtilsBean.java:2241) 
        at org.apache.commons.beanutils.PropertyUtilsBean.getIntrospectionData(PropertyUtilsBean.java:2226) 
        at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:954) 
        at org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptor(PropertyUtils.java:498) 
        at com.ceridwen.circulation.SIP.messages.Message.encode(Message.java:307) 
        at com.ceridwen.circulation.SIP.messages.Message.encode(Message.java:285) 
        at com.ceridwen.circulation.SIP.transport.Connection.send(Connection.java:215) 
        at com.guia.app.activities.TestActivity$performCheckOut$1$1.invokeSuspend(TestActivity.kt:65) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at android.os.Handler.handleCallback(Handler.java:761) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6617) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

it is triggered by the following lines from your example

`scStatusResponse = connection.send(scStatusRequest)` and `checkOutResponse = connection.send(checkOutRequest)`

Do you have any idea what might it be that is causing this issue?
Thanks in advance

**Comment by chuxubank** [comment]
Seemed you are using it on Android, you can try my project https://github.com/chuxubank/sip-droid which resolve the issue.
